PLATFORMS = {
    # ============ 国内平台 ============
    "wechat": {
        "name": "微信",
        "name_en": "WeChat",
        "css_file": "wechat.css",
        "logo": "img/logos/wechat.svg",
        "primary_color": "#07C160",
        "bg_color": "#EDEDED",
        "category": "domestic",
        "login_title": "登录微信",
        "register_title": "注册微信",
        "fields": {
            "username_label": "微信号/手机号/QQ号",
            "password_label": "密码",
            "email_label": "邮箱",
        },
        "button_text_login": "登录",
        "button_text_register": "注册",
    },
    "qq": {
        "name": "QQ",
        "name_en": "QQ",
        "css_file": "qq.css",
        "logo": "img/logos/qq.svg",
        "primary_color": "#12B7F5",
        "bg_color": "#F0F8FF",
        "category": "domestic",
        "login_title": "QQ登录",
        "register_title": "QQ注册",
        "fields": {
            "username_label": "QQ号/手机号/邮箱",
            "password_label": "密码",
            "email_label": "邮箱",
        },
        "button_text_login": "登 录",
        "button_text_register": "注 册",
    },
    "alipay": {
        "name": "支付宝",
        "name_en": "Alipay",
        "css_file": "alipay.css",
        "logo": "img/logos/alipay.svg",
        "primary_color": "#1677FF",
        "bg_color": "#F5F5F5",
        "category": "domestic",
        "login_title": "登录支付宝",
        "register_title": "注册支付宝",
        "fields": {
            "username_label": "手机号/邮箱",
            "password_label": "登录密码",
            "email_label": "邮箱",
        },
        "button_text_login": "登录",
        "button_text_register": "注册",
    },
    "taobao": {
        "name": "淘宝",
        "name_en": "Taobao",
        "css_file": "taobao.css",
        "logo": "img/logos/taobao.svg",
        "primary_color": "#FF5000",
        "bg_color": "#FFF5F0",
        "category": "domestic",
        "login_title": "登录淘宝",
        "register_title": "注册淘宝",
        "fields": {
            "username_label": "手机号/会员名",
            "password_label": "密码",
            "email_label": "邮箱",
        },
        "button_text_login": "登录",
        "button_text_register": "注册",
    },
    "douyin": {
        "name": "抖音",
        "name_en": "Douyin",
        "css_file": "douyin.css",
        "logo": "img/logos/douyin.svg",
        "primary_color": "#000000",
        "bg_color": "#F8F8F8",
        "category": "domestic",
        "login_title": "登录抖音",
        "register_title": "注册抖音",
        "fields": {
            "username_label": "手机号/抖音号",
            "password_label": "密码",
            "email_label": "邮箱",
        },
        "button_text_login": "登录",
        "button_text_register": "注册",
    },
    "weibo": {
        "name": "微博",
        "name_en": "Weibo",
        "css_file": "weibo.css",
        "logo": "img/logos/weibo.svg",
        "primary_color": "#FF8200",
        "bg_color": "#FFF8F0",
        "category": "domestic",
        "login_title": "登录微博",
        "register_title": "注册微博",
        "fields": {
            "username_label": "手机号/邮箱",
            "password_label": "密码",
            "email_label": "邮箱",
        },
        "button_text_login": "登录",
        "button_text_register": "注册",
    },
    # ============ 国际平台 ============
    "google": {
        "name": "Google",
        "name_en": "Google",
        "css_file": "google.css",
        "logo": "img/logos/google.svg",
        "primary_color": "#4285F4",
        "bg_color": "#FFFFFF",
        "category": "international",
        "login_title": "Sign in",
        "register_title": "Create your Google Account",
        "fields": {
            "username_label": "Username",
            "password_label": "Password",
            "email_label": "Email",
        },
        "button_text_login": "Sign in",
        "button_text_register": "Create account",
    },
    "github": {
        "name": "GitHub",
        "name_en": "GitHub",
        "css_file": "github.css",
        "logo": "img/logos/github.svg",
        "primary_color": "#238636",
        "bg_color": "#0D1117",
        "category": "international",
        "login_title": "Sign in to GitHub",
        "register_title": "Create your account",
        "fields": {
            "username_label": "Username",
            "password_label": "Password",
            "email_label": "Email",
        },
        "button_text_login": "Sign in",
        "button_text_register": "Sign up",
    },
    "apple": {
        "name": "Apple",
        "name_en": "Apple",
        "css_file": "apple.css",
        "logo": "img/logos/apple.svg",
        "primary_color": "#0071E3",
        "bg_color": "#FFFFFF",
        "category": "international",
        "login_title": "Sign in with Apple ID",
        "register_title": "Create Your Apple ID",
        "fields": {
            "username_label": "Apple ID",
            "password_label": "Password",
            "email_label": "Email",
        },
        "button_text_login": "Sign In",
        "button_text_register": "Continue",
    },
    "facebook": {
        "name": "Facebook",
        "name_en": "Facebook",
        "css_file": "facebook.css",
        "logo": "img/logos/facebook.svg",
        "primary_color": "#1877F2",
        "bg_color": "#F0F2F5",
        "category": "international",
        "login_title": "Log into Facebook",
        "register_title": "Create a new account",
        "fields": {
            "username_label": "Username",
            "password_label": "Password",
            "email_label": "Email",
        },
        "button_text_login": "Log In",
        "button_text_register": "Sign Up",
    },
    "twitter": {
        "name": "X (Twitter)",
        "name_en": "X",
        "css_file": "twitter.css",
        "logo": "img/logos/twitter.svg",
        "primary_color": "#000000",
        "bg_color": "#FFFFFF",
        "category": "international",
        "login_title": "Sign in to X",
        "register_title": "Create your account",
        "fields": {
            "username_label": "Username",
            "password_label": "Password",
            "email_label": "Email",
        },
        "button_text_login": "Sign in",
        "button_text_register": "Create account",
    },
    "microsoft": {
        "name": "Microsoft",
        "name_en": "Microsoft",
        "css_file": "microsoft.css",
        "logo": "img/logos/microsoft.svg",
        "primary_color": "#0078D4",
        "bg_color": "#F2F2F2",
        "category": "international",
        "login_title": "Sign in",
        "register_title": "Create account",
        "fields": {
            "username_label": "Username",
            "password_label": "Password",
            "email_label": "Email",
        },
        "button_text_login": "Sign in",
        "button_text_register": "Next",
    },
}
